modLoader = "javafml"
loaderVersion = "${loader_version_range}"

license="${mod_license}"

[[mods]]
modId = "cleanertooltips"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
logoFile = "icon.png"

[[dependencies.cleanertooltips]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.200,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cleanertooltips]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"