modLoader = "javafml"
loaderVersion = "[1,)"

license="MIT"

[[mods]]
modId = "${mod_id}"
version="${version}"
displayName="${mod_name}"
authors="${mod_author}"
description='''${description}'''
logoFile = "icon.png"

[[mixins]]
config = "cleanertooltips.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.200,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "cloth_config"
type = "required"
versionRange = "[15.0.0,)"
ordering = "AFTER"
side = "BOTH"